export interface FormattedError {
  title: string;
  message: string;
  isQuotaError: boolean;
  consoleUrl?: string;
  rawError?: string;
}

export const FIREBASE_CONSOLE_UPGRADE_URL = "https://console.firebase.google.com/project/mhs1-dmc/firestore/databases/ai-studio-mhs1bigdata-b097cba8-6fe0-43e2-ad20-e20681250b82/data?openUpgradeDialog=true";

export function formatFirestoreError(error: any): FormattedError {
  let errorStr = '';
  if (typeof error === 'string') {
    errorStr = error;
  } else if (error instanceof Error) {
    errorStr = error.message;
  } else {
    try {
      errorStr = JSON.stringify(error);
    } catch (e) {
      errorStr = String(error);
    }
  }

  // Check if errorStr is a JSON string generated by handleFirestoreError
  if (errorStr.trim().startsWith('{') && errorStr.trim().endsWith('}')) {
    try {
      const parsed = JSON.parse(errorStr);
      if (parsed.error) {
        errorStr = typeof parsed.error === 'string' ? parsed.error : JSON.stringify(parsed.error);
      }
    } catch (e) {}
  }

  const isQuotaExceeded =
    errorStr.includes('Quota limit exceeded') ||
    errorStr.includes('Quota exceeded') ||
    errorStr.includes('quota metric') ||
    errorStr.includes('resource-exhausted') ||
    errorStr.includes('Free daily read units per project');

  if (isQuotaExceeded) {
    return {
      title: '⚠️ โควตาการอ่านข้อมูลของ Firebase Firestore ในวันนี้เต็มแล้ว (Quota Exceeded)',
      message: 'ปริมาณการอ่านข้อมูลของระบบในแผนบริการฟรีรายวัน (Free Tier / Spark Plan) ได้ใช้งานครบโควตาแล้ว ระบบจะรีเซ็ตโควตาโดยอัตโนมัติในวันถัดไป หรือผู้ดูแลระบบสามารถกดอัปเกรดแผนบริการได้ที่ Firebase Console',
      isQuotaError: true,
      consoleUrl: FIREBASE_CONSOLE_UPGRADE_URL,
      rawError: errorStr
    };
  }

  return {
    title: 'เกิดข้อผิดพลาดในการเชื่อมต่อฐานข้อมูล',
    message: errorStr,
    isQuotaError: false,
    rawError: errorStr
  };
}
